services:
  client:
    build:
      context: ./ImStoryOnly
    ports:
      - 8001:8001
    container_name: oauth-client-app
    networks:
      - oauthnetwork


  server:
    build:
      context: ./mainApp
    ports:
      - 8000:8000
    volumes:
      - /app/src/
    container_name: oauth-server-app
    networks:
      - oauthnetwork

networks:
  oauthnetwork:
    driver: bridge