# Generated by Django 5.0.1 on 2024-01-31 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthprovider', '0002_token_delete_grant_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='token_body',
            field=models.UUIDField(default=uuid.UUID('368dcfa3-7ec8-46fb-b4f4-8ed26a441f86')),
        ),
    ]
