# Generated by Django 5.0.1 on 2024-01-31 15:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthprovider', '0003_token_activated_token_token_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 4, 1, 9, 752946)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_body',
            field=models.UUIDField(default=uuid.UUID('f46c9acf-a49e-4531-9be3-4edc5e931adb')),
        ),
    ]
