# Generated by Django 5.0.1 on 2024-01-31 15:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthprovider', '0004_alter_token_expires_at_alter_token_token_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='authorization_code',
            field=models.UUIDField(default=uuid.UUID('0e10c55a-de2a-4b9e-86f5-fcdd7301674e')),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 4, 1, 55, 602904)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_body',
            field=models.UUIDField(default=uuid.UUID('4ffde09c-30b2-4bfd-81da-2e9d60758819')),
        ),
    ]
