# Generated by Django 5.0.1 on 2024-02-01 03:56

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthprovider', '0006_alter_token_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='authorization_code',
            field=models.UUIDField(default=uuid.UUID('721516ce-12a2-4952-8a9f-c976833364e6')),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 16, 56, 20, 535917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_body',
            field=models.UUIDField(default=uuid.UUID('f4ed3d27-6f01-4c04-9884-59e2317cd79b')),
        ),
    ]
