# Generated by Django 5.0.1 on 2024-02-01 05:14

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthprovider', '0007_alter_token_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='authorization_code',
            field=models.UUIDField(default=uuid.UUID('4ef3f7c6-d40b-439d-b38a-1edd61b007e9')),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 18, 14, 13, 363436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_body',
            field=models.UUIDField(default=uuid.UUID('7c612a7b-9f4c-49a3-bcfe-ee4efcdc8997')),
        ),
    ]
