# Generated by Django 5.0.1 on 2024-02-02 05:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthprovider', '0009_alter_token_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_secret',
            field=models.UUIDField(default=uuid.UUID('800f637e-e093-409c-a0ce-13a02746f8c9'), unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='authorization_code',
            field=models.UUIDField(default=uuid.UUID('3df89f27-6654-4599-9c73-1233d0b92ad5')),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 18, 0, 59, 663053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_body',
            field=models.UUIDField(default=uuid.UUID('c4913a19-d762-4eb1-b34c-e4cae35a7ca1')),
        ),
    ]
