# Generated by Django 5.0.1 on 2024-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imstagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='full_description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='small_description',
            field=models.TextField(default='Remember to add small description to the image later', max_length=150),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='Image name', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
