# Generated by Django 5.0.1 on 2024-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imstagram', '0002_image_full_description_image_small_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='full_description',
            field=models.TextField(default='Remember to add description to your image later...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_description',
            field=models.TextField(default='Remember to add small description to the image later...', max_length=150),
        ),
    ]
