# Generated by Django 5.0.1 on 2024-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imstagram', '0003_remove_image_image_name_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
